version: "3"
services:
  proxy:
    restart: on-failure
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    restart: always
    environment:
      - APPLICATION_DATABASE_PASSWORD=${APPLICATION_DATABASE_PASSWORD}
      - APPLICATION_DATABASE_HOST=db
      - APPLICATION_ALLOWED_HOSTS=${APPLICATION_ALLOWED_HOSTS}
      - APPLICATION_SECRET_KEY=${APPLICATION_SECRET_KEY}
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${APPLICATION_DATABASE_PASSWORD}
    restart: unless-stopped

volumes:
  static_volume:
  db-volume:
