version: "3"
services:
  app:
    build: .
    networks:
      - backend
    ports:
      - "80:8000"
    environment:
      - APPLICATION_DATABASE_PASSWORD=${APPLICATION_DATABASE_PASSWORD}
      - APPLICATION_DATABASE_HOST=db
      - APPLICATION_ALLOWED_HOSTS=${APPLICATION_ALLOWED_HOSTS}
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${APPLICATION_DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-volume:
