name: Django CI

on: push

env:
  APPLICATION_SECRET_KEY: key
  APPLICATION_DATABASE_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          sudo apt install libgraphviz-dev graphviz pkg-config
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Prettier
        working-directory: ./backend
        run: |
          python -m black --check --diff --line-length 120 --skip-string-normalization .
      - name: Lint
        working-directory: ./backend
        run: |
          python -m flake8 --exclude .venv,budgetmapper/migrations --max-line-length=120
      - name: Setup
        working-directory: ./backend
        run: |
          python manage.py makemigrations
          python manage.py makemigrations budgetmapper
          python manage.py migrate
          python manage.py collectstatic
      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py test
      - name: Create ER graph
        working-directory: ./backend
        run: |
          if ! git diff --exit-code --quiet budgetmapper/models.py
          then
            python manage.py graph_models budgetmapper -g -o budgetmapper-model-graph.png
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add ./budgetmapper-model-graph.png
            git commit -m "(Auto) Update ER graph."
            git push
          fi
  create-er-graph:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      PYTHON_VERSION: "3.10"
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          sudo apt install libgraphviz-dev graphviz pkg-config
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Create ER graph
        working-directory: ./backend
        run: |
          if ! git diff --exit-code --quiet budgetmapper/models.py
          then
            python manage.py graph_models budgetmapper -g -o budgetmapper-model-graph.png
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add ./budgetmapper-model-graph.png
            git commit -m "(Auto) Update ER graph."
            git push
          fi
