name: Frontend CI

on: push

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        node: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "frontend/yarn.lock"
      - name: install
        run: yarn install

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "frontend/yarn.lock"
      - name: install
        run: yarn install

      - name: lint
        working-directory: ./frontend
        run: yarn lint
    needs: setup

  audit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "frontend/yarn.lock"
      - name: install
        run: yarn install

      - name: audit
        working-directory: ./frontend
        run: "yarn audit || :"
    needs: setup

  generate:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "frontend/yarn.lock"
      - name: install
        run: yarn install

      - name: generate
        working-directory: ./frontend
        run: yarn generate
    needs: setup
