name: Frontend CI

on: push

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        node: [14, 16]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All history

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "**/yarn.lock"

      - name: install
        working-directory: ./frontend
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: cache workspace
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
            ./frontend/packages/*/node_modules
            ./frontend/distributions/*/node_modules
            ./frontend/packages/*/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-nuxt-${{ github.sha }}

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "**/yarn.lock"

      - name: checkout
        uses: actions/checkout@master

      - name: restore workspace cache
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
            ./frontend/packages/*/node_modules
            ./frontend/distributions/*/node_modules
            ./frontend/packages/*/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-nuxt-${{ github.sha }}

      - name: lint
        working-directory: ./frontend
        run: yarn lint
    needs: setup

  audit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "**/yarn.lock"

      - name: checkout
        uses: actions/checkout@master

      - name: restore workspace cache
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/node_modules
            ./frontend/packages/*/node_modules
            ./frontend/distributions/*/node_modules
            ./frontend/packages/*/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-nuxt-${{ github.sha }}

      - name: audit
        working-directory: ./frontend
        run: "yarn audit || :"
    needs: setup

  generate:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "**/yarn.lock"

      - name: checkout
        uses: actions/checkout@master

      - name: restore workspace cache
        uses: actions/cache@v2
        with:
          path: |
            ./frontend/ node_modules
             ./frontend/packages/*/node_modules
             ./frontend/distributions/*/node_modules
             ./frontend/packages/*/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-nuxt-${{ github.sha }}

      - name: generate
        working-directory: ./frontend
        run: yarn generate
    needs: setup
