name: Frontend CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: "frontend/yarn.lock"
      - run: cd frontend && yarn install

      - name: audit
        working-directory: ./frontend
        run: "yarn audit || :"

      - name: lint
        working-directory: ./frontend
        run: yarn lint

      - name: generate
        working-directory: ./frontend
        run: yarn generate --fail-on-error
